= Framework с определённым числом запусков

Необходимо написать новый фреймворк, который будет запускать link:api/src/main/java/ru/hse/scheduled/api/annotation/Scheduled.java[`@Scheduled`] метод определённое число раз.
Количество раз контролируется параметром `times` аннотации `@Scheduled`, например:

[source,java]
----
public class MyDemo {
    @Scheduled(times = 10) // <1>
    public void sayHello() {
        // ...
    }
}
----

<1> Метод `sayHello` должен быть вызван 10 раз

== Функциональность times

Функциональность `times` -- опциональная у фреймворка.
Смотрите описание `times` в документации аннотации link:api/src/main/java/ru/hse/scheduled/api/annotation/Scheduled.java[`@Scheduled`].

Метод `supports(Feature)` возвращает `true`, если фреймворк поддерживает link:api/src/main/java/ru/hse/scheduled/api/Feature.java[`Feature`].

Чтобы узнать, поддерживает ли фреймворк функциональность `times` используйте метод `supports` интерфейса с аргументом `Feature.TIMES`.
Пример:

[source,java]
----
public static void test(Framework framework) {
    if (framework.supports(Feature.TIMES)) {
        System.out.println("Поддержка есть");
    } else {
        System.out.println("Поддержки нет");
    }
}
----

== Требования

. Новый фреймворк -- новый модуль в приложении: необходимо создать maven модуль и java-модуль.
Для реализации фреймворка можно наследовать link:impl/src/main/java/ru/hse/scheduled/impl/SimpleFramework.java[`SimpleFramework`]
. Реализовать новый фреймворк
. Переделать `client`, так, чтобы:
.. У `@Scheduled` метода был проставлен атрибут `times`
.. Метод `main` при запуске искал фреймворк и если:
... Фреймворка нет, выводил соответсвующее сообщение
... Фреймворк найден, но не поддерживает функциональность `times`, то выводится соответсвующее сообщение
... Фреймворк найден, и `times` поддерживается, то запускается демо-приложение
. В директории `scripts` написать скрипты для своей OS, которые запустят приложение для всех трёх случаев:
.. Когда фреймворк есть в `--module-path` и `times` поддерживается
.. Когда фреймворк есть в `--module-path`, но `times` не поддерживается
.. Когда фреймворк есть и `times` поддерживается

== Пример запуска

.Без фреймворка
[source,bash]
----
./scripts/no-framework.sh

Фреймворка нет
----

.С фреймворком, но без поддержки `times`
[source,bash]
----
./scripts/framework-no-times.sh

Фреймворк найден, но нет поддержки times
----

.С фреймворком
[source,bash]
----
./scripts/framework.sh

Hello! Time is 2024-04-06T19:00:17.065473217
Hello! Time is 2024-04-06T19:00:18.050233101
Hello! Time is 2024-04-06T19:00:19.050323509
Hello! Time is 2024-04-06T19:00:20.050378826
----

== Полезные ссылки

. https://www.baeldung.com/java-modularity#5-running-our-code[Java modularity. Running our code].
Здесь описывают, как необходимо запускать модульное Java-приложение с помощью опции `--module-path`
